run:
  name: cap_exp_2030_split_wacc_NDC
countries:
- NG
scenario:
  simpl:
  - ''
  ll:
  - copt
  clusters:
  - 10
  opts:
  - 1h
snapshots:
  start: '2024-01-01'
  end: '2025-01-01'
  inclusive: left
enable:
  retrieve_databundle: false
  download_osm_data: true
  retrieve_cutout: false
  build_cutout: false
  retrieve_cost_data: true
  retrieve_databundle_sector: false
  download_global_buildings: false
  build_natura_raster: true
  progress_bar: true
atlite:
  nprocesses: 4
  cutouts:
    cutout-2024-era5:
      module: era5
      dx: 0.3
      dy: 0.3
      time:
      - '2024-01-01'
      - '2025-01-01'
  default: cutout-2024-era5
renewable:
  onwind:
    cutout: auto
    resource:
      method: wind
      turbine: Vestas_V112_3MW
    capacity_per_sqkm: 3
    copernicus:
      grid_codes:
      - 20
      - 30
      - 40
      - 60
      - 100
      - 111
      - 112
      - 113
      - 114
      - 115
      - 116
      - 121
      - 122
      - 123
      - 124
      - 125
      - 126
      distance: 1000
      distance_grid_codes:
      - 50
    natura: true
    potential: simple
    clip_p_max_pu: 0.01
    extendable: true
  solar:
    cutout: auto
    resource:
      method: pv
      panel: CSi
      orientation: latitude_optimal
    capacity_per_sqkm: 4.6
    correction_factor: 1.0
    copernicus:
      grid_codes:
      - 20
      - 30
      - 40
      - 50
      - 60
      - 90
      - 100
    natura: true
    potential: simple
    clip_p_max_pu: 0.01
    extendable: true
  hydro:
    cutout: auto
    hydrobasins_level: 6
    resource:
      method: hydro
      hydrobasins: data/hydrobasins/hybas_world.shp
      flowspeed: 1.0
    carriers:
    - ror
    - hydro
    - PHS
    hydro_max_hours: energy_capacity_totals_by_country
    hydro_max_hours_default: 6.0
    clip_min_inflow: 1.0
    extendable: false
    normalization:
      method: eia
      year: 2023
    multiplier: 1.21
    hydro_min_inflow_pu: 1.0
conventional:
  CCGT:
    p_max_pu: 1.0
  OCGT:
    p_max_pu: 1.0
clustering:
  exclude_carriers:
  - oil
  - gas
  - coal
  remove_stubs: true
  p_threshold_drop_isolated: 100
base_network:
  min_voltage_rebase_voltage: 330000
load_options:
  source: demcast
  weather_year: 2024
  prediction_year: 2030
  scale: 2.07
electricity:
  conventional_efficiency:
    CCGT: 0.58
    OCGT: 0.31
lines:
  s_max_pu: 1.0
  custom_line_types: data/line_types.csv
  ac_types:
    330.0: ACSR Zebra 2-bundle 330.0
costs:
  year: 2030
  discountrate_groups:
    renewable:
      rate: 0.1379
      carriers:
      - solar
      - onwind
    hydro:
      rate: 0.1379
      carriers:
      - hydro
    battery:
      rate: 0.1379
      carriers:
      - battery
    fossil:
      rate: 0.1468
      carriers:
      - OCGT
      - CCGT
  marginal_cost:
    solar: 0
    onwind: 0
    offwind: 0.015
    hydro: 1.05
    coal: 72.9
    ror: 0
    oil: 4.23
    geothermal: 0.87
    biomass: 4.14
    nuclear: 3.46
    csp: 0.0
    OCGT: 6.18
    CCGT: 4.15
solving:
  options:
    load_shedding: 1.0
  solver:
    name: gurobi
    options: gurobi-default
validation:
  interconnectors:
    enable: false
co2:
  limit: 8800000.0
  base: 0.0
